// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6BGndVkXTvOnoDcsLmdQPZwuhK5IVRjA',
    appId: '1:614177920942:web:dbc0d5af827f25c3001a3f',
    messagingSenderId: '614177920942',
    projectId: 'pemrograman-mobile-321e0',
    authDomain: 'pemrograman-mobile-321e0.firebaseapp.com',
    storageBucket: 'pemrograman-mobile-321e0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6eiRb8ar2kMJGa7ilccgvmtKPelRPA94',
    appId: '1:614177920942:android:f5f5a78e56fcf42d001a3f',
    messagingSenderId: '614177920942',
    projectId: 'pemrograman-mobile-321e0',
    storageBucket: 'pemrograman-mobile-321e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr9QPujU_Q4fK6QaSq_YkGa5NdH_DiNNE',
    appId: '1:614177920942:ios:e4cbd8b893ed9c95001a3f',
    messagingSenderId: '614177920942',
    projectId: 'pemrograman-mobile-321e0',
    storageBucket: 'pemrograman-mobile-321e0.firebasestorage.app',
    iosBundleId: 'my.id.olanmaxrin.pert6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAr9QPujU_Q4fK6QaSq_YkGa5NdH_DiNNE',
    appId: '1:614177920942:ios:e4cbd8b893ed9c95001a3f',
    messagingSenderId: '614177920942',
    projectId: 'pemrograman-mobile-321e0',
    storageBucket: 'pemrograman-mobile-321e0.firebasestorage.app',
    iosBundleId: 'my.id.olanmaxrin.pert6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6BGndVkXTvOnoDcsLmdQPZwuhK5IVRjA',
    appId: '1:614177920942:web:54b1c029f34f84a6001a3f',
    messagingSenderId: '614177920942',
    projectId: 'pemrograman-mobile-321e0',
    authDomain: 'pemrograman-mobile-321e0.firebaseapp.com',
    storageBucket: 'pemrograman-mobile-321e0.firebasestorage.app',
  );
}
